---
- name: BasicTeXインストール
  homebrew_cask: name=basictex
# - name: texbinにパスを通す
#   shell: export PATH=/Library/texbin:$PATH
- name: tlmgr アップデート
  shell: tlmgr update --self --all
  become: yes
  environment:
    PATH: "/Library/TeX/texbin:{{ ansible_env.PATH }}"
- name: TeXパッケージインストール
  shell: tlmgr install collection-langjapanese latexmk ptex ptex2pdf jfontmaps jsclasses japanese-otf
  become: yes
  environment:
    PATH: "/Library/TeX/texbin:{{ ansible_env.PATH }}"
# - name: なんか実行
#   shell: perl cjk-gs-integrate.pl --link-texmf --force
#   sudo: yes
#   args:
#     chdir: /usr/local/texlive/2015/texmf-dist/scripts/cjk-gs-integrate
# - name: おまじない
#   shell: mktexlsr
#   sudo: yes
# - name: ヒラギノその1
#   shell: updmap-sys --setoption kanjiEmbed hiragino-elcapitan
#   sudo: yes
# - name: ヒラギノその2
#   shell: updmap-sys --setoption kanjiEmbed hiragino-elcapitan-pron
#   sudo: yes
